---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging 
summary: Familiarize-se com o carregamento, o modelo de consumo, os preços e as configurações das licenças baseadas na capacidade. 
---
= Saiba mais sobre licenças baseadas em capacidade para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve estar familiarizado com o carregamento e uso de capacidade para licenças baseadas em capacidade



== Modelos de consumo

Pacotes de licenciamento baseados em capacidade estão disponíveis com os seguintes modelos de consumo:

* *BYOL*: Traga sua própria licença (BYOL). Uma licença adquirida na NetApp que pode ser usada para implantar o Cloud Volumes ONTAP em qualquer provedor de nuvem.


ifdef::azure[]

Observe que o pacote otimizado não está disponível com o BYOL.

endif::azure[]

* *PAYGO*: Uma assinatura paga conforme o uso (PAYGO) é uma assinatura por hora do mercado do seu provedor de nuvem.
* *Anual*: Um contrato anual do mercado do seu provedor de nuvem.


Observe o seguinte:

* Se você adquirir uma licença da NetApp (BYOL), também precisará assinar a oferta PAYGO no mercado do seu provedor de nuvem.
+
Sua licença sempre será cobrada primeiro, mas você será cobrado pela taxa por hora no mercado nestes casos:

+
** Se você exceder sua capacidade licenciada
** Se o prazo da sua licença expirar


* Se você tiver um contrato anual de um mercado, _All_ Cloud Volumes ONTAP sistemas que você implantar serão cobrados contra esse contrato. Você não pode misturar e combinar um contrato de mercado anual com o BYOL.
* Somente sistemas de nó único com BYOL são compatíveis nas regiões da China.




== Mudando pacotes

Após a implantação, você pode alterar o pacote de um sistema Cloud Volumes ONTAP que usa licenciamento baseado em capacidade. Por exemplo, se você implantou um sistema Cloud Volumes ONTAP com o pacote Essentials, poderá alterá-lo para o pacote Professional se a sua empresa precisar ser alterada.

link:task-manage-capacity-licenses.html["Saiba como alterar os métodos de carregamento"].

Para obter informações sobre como converter licenças baseadas em nós para baseadas em capacidade, consulte



== Preços e configurações compatíveis

Para obter detalhes sobre preços, https://bluexp.netapp.com/pricing/["Site da NetApp BlueXP "^] visite .

Pacotes de licenciamento baseados em capacidade estão disponíveis com o Cloud Volumes ONTAP 9,7 e versões posteriores.



=== VMs de storage

* Não há custos adicionais de licenciamento para VMs de storage de fornecimento de dados (SVMs) adicionais, mas há uma cobrança de capacidade mínima de 4 TIB por SVM de fornecimento de dados.
* As SVMs de recuperação de desastres são cobradas de acordo com a capacidade provisionada.




=== Pares HA

Para pares de HA, você só será cobrado pela capacidade provisionada em um nó. Você não será cobrado pelos dados espelhados de forma síncrona para o nó do parceiro.



=== FlexClone e FlexCache volumes

* Não será cobrado pela capacidade usada pelo FlexClone volumes.
* Os volumes FlexCache de origem e destino são considerados dados primários e cobrados de acordo com o espaço provisionado.




== Limite de capacidade

Com esse modelo de licenciamento, cada sistema Cloud Volumes ONTAP individual dá suporte a até 2 PIB de capacidade por meio de discos e disposição em camadas no storage de objetos.

Não há limite máximo de capacidade quando se trata da própria licença.



== Número máximo de sistemas

Com o licenciamento baseado em capacidade, o número máximo de sistemas Cloud Volumes ONTAP é limitado a 20 por conta do NetApp. Um _System_ é um par de HA do Cloud Volumes ONTAP, um sistema de nó único do Cloud Volumes ONTAP ou quaisquer VMs de storage adicionais que você criar. A VM de armazenamento padrão não conta com o limite. Este limite aplica-se a todos os modelos de licenciamento.

Por exemplo, digamos que você tenha três ambientes de trabalho:

* Um sistema Cloud Volumes ONTAP de nó único com uma VM de storage (essa é a VM de storage padrão criada quando você implanta o Cloud Volumes ONTAP)
+
Este ambiente de trabalho conta como um sistema.

* Um sistema Cloud Volumes ONTAP de nó único com duas VMs de storage (a VM de storage padrão e uma VM de storage adicional criada por você)
+
Esse ambiente de trabalho conta como dois sistemas: Um para o sistema de nó único e outro para a VM de storage adicional.

* Um par de HA do Cloud Volumes ONTAP com três VMs de storage (a VM de storage padrão e duas VMs de storage adicionais criadas por você)
+
Esse ambiente de trabalho conta como três sistemas: Um para o par de HA e dois para as VMs de storage adicionais.



São seis sistemas no total. Você teria então espaço para um sistema 14 adicional em sua conta.

Se você tiver uma implantação grande que exija mais de 20 sistemas, entre em Contato com o representante de sua conta ou com a equipe de vendas.

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["Saiba mais sobre as contas do NetApp"^].



== Notas sobre o carregamento

Os detalhes a seguir podem ajudá-lo a entender como o carregamento funciona com licenciamento baseado em capacidade.



=== Carga mínima

Há uma cobrança mínima de 4 TIB para cada VM de storage de fornecimento de dados que tenha pelo menos um volume primário (leitura-gravação). Se a soma dos volumes primários for inferior a 4 TIB, o BlueXP  aplicará a carga mínima de 4 TIB a essa VM de armazenamento.

Se você ainda não provisionou nenhum volume, a cobrança mínima não se aplica.

Para o pacote Essentials, a taxa de capacidade mínima de 4 TIB não se aplica a VMs de armazenamento que contêm apenas volumes secundários (proteção de dados). Por exemplo, se você tiver uma VM de storage com 1 TIB de dados secundários, então você será cobrado apenas por 1 TIB de dados. Com todos os outros tipos de pacotes não essenciais (otimizado e profissional), a capacidade mínima de carregamento de 4 TIB aplica-se independentemente do tipo de volume.



=== Excesso de idade

Se você exceder sua capacidade BYOL ou se sua licença expirar, será cobrado por excesso de idade à taxa por hora com base na assinatura do marketplace.



=== Pacote Essentials

Com o pacote Essentials, você é cobrado pelo tipo de implantação (HA ou nó único) e pelo tipo de volume (primário ou secundário). Os preços de alta para baixa estão na seguinte ordem: _Essentials Primary HA_, _Essentials Primary Single Node_, _Essentials Secondary HA_ e _Essentials Secondary Single Node_. Como alternativa, quando você compra um contrato de mercado ou aceita uma oferta privada, as taxas de capacidade são as mesmas para qualquer tipo de implantação ou volume.

O licenciamento é baseado inteiramente no tipo de volume criado nos sistemas Cloud Volumes ONTAP:

* Nó único Essentials: Volumes de leitura/gravação criados em um sistema Cloud Volumes ONTAP usando apenas um nó ONTAP.
* Essentials HA: Volumes de leitura/gravação usando dois nós de ONTAP que podem fazer failover uns para os outros para acesso a dados sem interrupções.
* Nó único secundário do Essentials: Volumes do tipo de proteção de dados (normalmente volumes de destino SnapMirror ou SnapVault que são somente leitura) criados em um sistema Cloud Volumes ONTAP usando apenas um nó ONTAP.
+

NOTE: Se um volume somente leitura/DP se tornar um volume primário, o BlueXP  o considera como dados primários e os custos de carregamento são calculados com base no tempo em que o volume estava no modo de leitura/gravação. Quando o volume é novamente feito somente leitura/DP, a BlueXP  considera-o como dados secundários novamente e cobra de acordo com a licença mais adequada na carteira digital.

* Essentials secundário HA: Volumes do tipo de proteção de dados (DP) (normalmente volumes de destino SnapMirror ou SnapVault somente leitura) criados em um sistema Cloud Volumes ONTAP usando dois nós de ONTAP que podem fazer failover entre si para acesso a dados sem interrupções.


Observe estes pontos:

* Cobrança mínima: Há uma cobrança mínima de 4 TIB para cada VM de storage de fornecimento de dados que tenha pelo menos um volume primário (leitura-gravação). Para o pacote Essentials, essa cobrança mínima não se aplica às VMs de storage somente com volumes secundários (proteção de dados).
* Excedentes: Se a capacidade licenciada for excedida, os excedentes são cobrados pelas taxas de mercado, com preferência pela utilização da capacidade disponível de outras licenças em primeiro lugar.
* FlexClone e FlexCache volumes: O FlexClone volumes não é cobrado. Os volumes FlexCache de origem e destino são considerados dados primários e são cobrados de acordo com o espaço provisionado.
* Carregamento de pares HA: Para pares de HA, somente a capacidade provisionada em um nó é cobrada. Os dados espelhados de forma síncrona para o nó do parceiro não são cobrados.


.BYOL
Se você comprou uma licença Essentials da NetApp (BYOL) e exceder a capacidade licenciada para esse tipo de implantação e volume, a carteira digital da BlueXP  cobra sobretaxas a uma licença Essentials de preço mais alto (se você tiver uma e houver capacidade disponível). Isso acontece porque primeiro usamos a capacidade disponível que você já comprou como capacidade pré-paga antes de cobrar no mercado. Se não houver capacidade disponível com sua licença BYOL, a capacidade excedida será cobrada nas taxas horárias sob demanda do mercado (PAYGO) e adicionará custos à sua fatura mensal.

Aqui está um exemplo. Digamos que você tenha as seguintes licenças para o pacote Essentials:

* Uma licença 500 TIB _Essentials Secondary HA_ que tem 500 TIB de capacidade comprometida
* Uma licença de nó único TIB _Essentials de 500 TIB que tenha apenas 100 TIB de capacidade comprometida


Outro 50 TIB é provisionado em um par de HA com volumes secundários. Em vez de cobrar esse 50 TIB ao PAYGO, a carteira digital BlueXP  cobra o excesso de TIB de 50 TIB contra a licença _Essentials Single Node_. Essa licença tem um preço superior ao _Essentials Secondary HA_, mas está fazendo uso de uma licença que você já comprou, e não adicionará custos à sua conta mensal.

Na carteira digital BlueXP , esse 50 TIB será mostrado como cobrado com a licença _Essentials Single Node_.

Aqui está outro exemplo. Digamos que você tenha as seguintes licenças para o pacote Essentials:

* Uma licença 500 TIB _Essentials Secondary HA_ que tem 500 TIB de capacidade comprometida
* Uma licença de nó único TIB _Essentials de 500 TIB que tenha apenas 100 TIB de capacidade comprometida


Outro 100 TIB é provisionado em um par de HA com volumes primários. A licença que você comprou não tem a capacidade comprometida _Essentials Primary HA_. A licença _Essentials Primary HA_ tem um preço superior às licenças _Essentials Primary Single Node_ e _Essentials Secondary HA_.

Neste exemplo, a carteira digital BlueXP  cobra sobretaxas à taxa de mercado para os 100 TIB adicionais. As taxas de excesso de idade aparecerão na sua conta mensal.

.Contratos de mercado ou ofertas privadas
Se você comprou uma licença Essentials como parte de um contrato de mercado ou uma oferta privada, a lógica BYOL não se aplica e você deve ter o tipo de licença exato para o uso. O tipo de licença inclui o tipo de volume (primário ou secundário) e o tipo de implantação (HA ou nó único).

Por exemplo, digamos que você implante uma instância do Cloud Volumes ONTAP com a licença Essentials. Depois, você provisiona volumes de leitura e gravação (nó único primário) e volumes somente leitura (nó único secundário). Seu contrato de mercado ou oferta privada deve incluir capacidade para _Essentials Single Node_ e _Essentials Secondary Single Node_ para cobrir a capacidade provisionada. Qualquer capacidade provisionada que não faça parte do seu contrato de mercado ou oferta privada será cobrada de acordo com as taxas por hora sob demanda (PAYGO) e adicionará custos à sua fatura mensal.
