---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha uma configuração que atenda às suas necessidades. 
---
= Licenciamento para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha um modelo de consumo que atenda às suas necessidades.



== Visão geral do licenciamento

As opções de licenciamento a seguir estão disponíveis para novos clientes.

Licenciamento baseado em capacidade:: Pague por vários sistemas Cloud Volumes ONTAP na sua conta do NetApp por capacidade provisionada. Inclui a capacidade de adquirir serviços de dados de nuvem complementares. Para obter mais informações sobre modelos de consumo em licenças baseadas em capacidade, link:concept-licensing-charging.html["Saiba mais sobre licenças baseadas em capacidade"]consulte .
Inscrição no Keystone:: Um serviço baseado em subscrição com pagamento conforme o uso que proporciona uma experiência otimizada de nuvem híbrida para pares de alta disponibilidade (HA).


As seções a seguir fornecem mais detalhes sobre cada uma dessas opções.


NOTE: O suporte não está disponível para o uso de recursos licenciados sem uma licença.



== Licenciamento baseado em capacidade

Os pacotes de licenciamento baseados em capacidade permitem que você pague por Cloud Volumes ONTAP por TIB de capacidade. A licença está associada à sua conta NetApp e permite que você carregue vários sistemas contra a licença, contanto que a capacidade suficiente esteja disponível através da licença.

Por exemplo, você pode comprar uma única licença TIB de 20 TB, implantar quatro sistemas Cloud Volumes ONTAP e alocar um volume de TIB de 5 TB para cada sistema, totalizando 20 TIB. A capacidade está disponível para os volumes em cada sistema Cloud Volumes ONTAP implantado nessa conta.

O licenciamento baseado em capacidade está disponível na forma de um _pacote_. Ao implantar um sistema Cloud Volumes ONTAP, você pode escolher entre vários pacotes de licenciamento com base nas necessidades da sua empresa.


NOTE: Embora o uso real e a medição dos produtos e serviços gerenciados no BlueXP  sejam sempre calculados em GiB e TIB, os termos GB/GiB e TB/TIB são usados de forma intercambiável. Isso é refletido nas listagens do Cloud Marketplace, cotações de preços, descrições de listagem e em outra documentação de suporte.



=== Pacotes

Os seguintes pacotes baseados em capacidade estão disponíveis para o Cloud Volumes ONTAP. Para obter mais informações sobre pacotes de licença baseados em capacidade, link:concept-licensing-charging.html["Saiba mais sobre licenças baseadas em capacidade"]consulte .

Para obter uma lista de tipos de VM suportados com os seguintes pacotes baseados em capacidade, consulte:

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurações compatíveis no Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurações compatíveis no Google Cloud"^]


endif::gcp[]



==== Freemium

Fornece todos os recursos do Cloud Volumes ONTAP gratuitamente da NetApp (taxas de provedor de nuvem ainda se aplicam). Um pacote Freemium tem estas caraterísticas:

* Nenhuma licença ou contrato é necessário.
* O suporte do NetApp não está incluído.
* Você está limitado a 500 GiB de capacidade provisionada por sistema Cloud Volumes ONTAP.
* Você pode usar até 10 sistemas Cloud Volumes ONTAP com a oferta Freemium por conta NetApp, para qualquer provedor de nuvem.
* Se a capacidade provisionada para um sistema Cloud Volumes ONTAP exceder 500 GiB, o BlueXP  converte o sistema em um pacote Essentials.
+
Assim que um sistema é convertido para o pacote Essentials, link:concept-licensing-charging.html#minimum-charge["carregamento mínimo"] aplica-se a ele.

+
Um sistema Cloud Volumes ONTAP que foi convertido em um pacote Essentials não pode ser comutado de volta para Freemium mesmo que a capacidade provisionada seja reduzida para menos de 500 GiB. Outros sistemas com menos de 500 GiB de capacidade provisionada permanecem no Freemium (desde que sejam implantados usando a oferta Freemium).





==== Essenciais

Você pode pagar por capacidade em várias configurações diferentes:

* Escolha sua configuração do Cloud Volumes ONTAP:
+
** Um único nó ou sistema de HA
** Storage de arquivos e blocos ou dados secundários para recuperação de desastres (DR)


* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra




==== Otimizado

Pague por operações de e/S e capacidade provisionadas separadamente.

* Nó único ou HA da Cloud Volumes ONTAP
* O carregamento baseia-se em dois componentes de custo: Armazenamento e utilização (e/S).
+
Você não será cobrado por e/S relacionadas à replicação de dados (SnapMirror), backups (SnapVault) ou NDMP.



ifdef::azure[]

* Disponível no Azure Marketplace como uma oferta de pagamento conforme o uso ou como um contrato anual


endif::azure[]

ifdef::gcp[]

* Disponível no Google Cloud Marketplace como uma oferta de pagamento conforme o uso ou como um contrato anual


endif::gcp[]

* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra




==== Profissional

Pague por capacidade por qualquer tipo de configuração Cloud Volumes ONTAP com backups ilimitados.

* Fornece licenciamento para qualquer configuração do Cloud Volumes ONTAP
+
Nó único ou HA com carregamento de capacidade para volumes primários e secundários à mesma taxa

* Inclui backups de volume ilimitados usando backup e recuperação do BlueXP , mas apenas para sistemas Cloud Volumes ONTAP que usam o pacote profissional.
+

NOTE: É necessária uma subscrição de pagamento conforme o uso (PAYGO) para a recuperação e o backup do BlueXP , no entanto, não haverá cobrança pelo uso deste serviço. Para obter mais informações sobre como configurar o licenciamento para backup e recuperação do BlueXP , https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Configure o licenciamento para backup e recuperação do BlueXP "^] consulte .

* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra




=== Disponibilidade de licenças baseadas em capacidade

A disponibilidade das licenças PAYGO e BYOL para sistemas Cloud Volumes ONTAP exige que o conetor BlueXP  esteja ativo e em execução. Para obter mais informações, https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["Saiba mais sobre conetores"^] consulte .



=== Como começar

Saiba como começar a usar o licenciamento baseado em capacidade:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure o licenciamento para o Cloud Volumes ONTAP na AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure o licenciamento para o Cloud Volumes ONTAP no Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure o licenciamento para o Cloud Volumes ONTAP no Google Cloud"]


endif::gcp[]



== Inscrição no Keystone

Um serviço baseado em subscrição com pagamento conforme o uso que oferece uma experiência de nuvem híbrida otimizada para quem prefere modelos de consumo de despesas operacionais para CapEx adiantado ou aluguel.

O carregamento é baseado no tamanho da sua capacidade comprometida com um ou mais pares de HA da Cloud Volumes ONTAP na assinatura do Keystone.

A capacidade provisionada para cada volume é agregada e comparada com a capacidade comprometida periodicamente na sua assinatura do Keystone, e quaisquer excedentes são cobrados como o pico da sua assinatura do Keystone.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Saiba mais sobre o NetApp Keystone"^].



=== Configurações compatíveis

As assinaturas do Keystone são compatíveis com pares de HA. Esta opção de licenciamento não é suportada com sistemas de nó único no momento.



=== Limite de capacidade

Cada sistema Cloud Volumes ONTAP individual dá suporte a até 2 PIB de capacidade por meio de discos e disposição em camadas no storage de objetos.



=== Como começar

Saiba como começar a usar uma assinatura do Keystone:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure o licenciamento para o Cloud Volumes ONTAP na AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure o licenciamento para o Cloud Volumes ONTAP no Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure o licenciamento para o Cloud Volumes ONTAP no Google Cloud"]


endif::gcp[]



== Licenciamento baseado em nó

O licenciamento baseado em nó é o modelo de licenciamento da geração anterior que permitiu licenciar o Cloud Volumes ONTAP por nó. Este modelo de licenciamento não está disponível para novos clientes. O carregamento por nó foi substituído pelos métodos de carregamento por capacidade adicional descritos acima.

A NetApp planejou o fim da disponibilidade (EOA) e o suporte (EOS) do licenciamento baseado em nós. Após a EOA e a EOS, as licenças baseadas em nós precisarão ser convertidas em licenças baseadas em capacidade.

Para obter informações, https://mysupport.netapp.com/info/communications/CPC-00589.html["Comunicado do cliente: CPC-00589"^] consulte .



=== Término da disponibilidade de licenças baseadas em nós

A partir de 11 de novembro de 2024, a disponibilidade limitada de licenças baseadas em nós foi encerrada. O suporte para licenciamento baseado em nós termina em 31 de dezembro de 2024.

Se você tiver um contrato válido baseado em nós que se estende além da data EOA, você pode continuar a usar a licença até que o contrato expire. Uma vez que o contrato expirar, será necessário fazer a transição para o modelo de licenciamento baseado em capacidade. Se não tiver um contrato de longo prazo para um nó Cloud Volumes ONTAP, é importante planear a sua conversão antes da data EOS.

Saiba mais sobre cada tipo de licença e o impactos da EOA sobre ele a partir desta tabela:

[cols="2*"]
|===
| Tipo de licença | Impacto após EOA 


 a| 
Licença válida baseada em nó adquirida por meio do bring Your own license (BYOL)
 a| 
A licença permanece válida até a expiração. As licenças não utilizadas existentes baseadas em nós podem ser usadas para implantar novos sistemas Cloud Volumes ONTAP.



 a| 
Licença baseada em nó expirada adquirida por meio do BYOL
 a| 
Você não terá o direito de implantar novos sistemas Cloud Volumes ONTAP usando esta licença. Os sistemas existentes podem continuar a funcionar, mas não receberá qualquer suporte ou atualizações para os seus sistemas após a data EOS.



 a| 
Licença válida baseada em nó com assinatura PAYGO
 a| 
Deixará de receber o suporte NetApp após a data EOS, até que faça a transição para uma licença baseada em capacidade.

|===
.Exclusões
A NetApp reconhece que certas situações exigem consideração especial, e a EOA e EOS de licenciamento baseado em nós não se aplicarão aos seguintes casos:

* Clientes do setor público dos EUA
* Implantações em modo privado
* Implementações da região da China do Cloud Volumes ONTAP na AWS


Para esses cenários específicos, a NetApp oferecerá suporte para atender aos requisitos exclusivos de licenciamento em conformidade com as obrigações contratuais e as necessidades operacionais.


NOTE: Mesmo nesses cenários, novas licenças baseadas em nós e renovações de licença são válidas por um máximo de um ano a partir da data de aprovação.



== Conversão de licença

O BlueXP  permite uma conversão contínua de licenças baseadas em nós para capacidade com base na ferramenta de conversão de licenças. Para obter informações sobre a EOA do licenciamento baseado em nós, link:concept-licensing.html#end-of-availability-of-node-based-licenses["Término da disponibilidade de licenças baseadas em nós"]consulte .

Antes da transição, é bom se familiarizar com a diferença entre os dois modelos de licenciamento. O licenciamento baseado em nó inclui capacidade fixa para cada instância do ONTAP, o que pode restringir a flexibilidade. O licenciamento baseado em capacidade, por outro lado, permite um pool compartilhado de storage em várias instâncias, oferecendo maior flexibilidade, otimizando a utilização de recursos e reduzindo o potencial de penalidades financeiras ao redistribuir cargas de trabalho. O carregamento baseado em capacidade ajusta-se perfeitamente às mudanças nos requisitos de armazenamento.

Para saber como pode efetuar esta conversão, link:task-convert-node-capacity.html["Converta uma licença baseada em nó Cloud Volumes ONTAP em licença baseada em capacidade"]consulte .


NOTE: A conversão de um sistema de licenças baseadas em capacidade para licenças baseadas em nós não é suportada.
