---
sidebar: sidebar 
permalink: concept-azure-mktplace-direct.html 
keywords: azure marketplace direct, cvo in azure marketplace 
summary:  
---
= Saiba mais sobre as opções de implantação do Cloud Volumes ONTAP no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp oferece duas opções para implantar o Cloud Volumes ONTAP no Azure. A Cloud Volumes ONTAP tradicionalmente conta com o BlueXP  para implantação e orquestração. A partir do Cloud Volumes ONTAP 9.16.1, você pode aproveitar a implantação direta do marketplace do Azure, um processo simplificado que fornece acesso a um conjunto limitado, mas ainda poderoso, de recursos e opções do Cloud Volumes ONTAP.

Ao implantar o Cloud Volumes ONTAP diretamente do marketplace do Azure, não é necessário configurar o BlueXP  Connector ou atender a outros critérios de segurança e integração necessários para implantar o Cloud Volumes ONTAP por meio do BlueXP . Com o marketplace do Azure, você pode implantar o Cloud Volumes ONTAP rapidamente com apenas alguns cliques e explorar seus principais recursos e funcionalidades no seu ambiente.

Ao concluir a implantação no marketplace do Azure, você pode descobrir esses sistemas no BlueXP . Após a descoberta, você pode gerenciá-los como ambientes de trabalho e aproveitar todos os recursos do BlueXP . link:task-deploy-cvo-azure-mktplc.html["Descubra os sistemas implantados no BlueXP "]Consulte a .

Aqui está a comparação de recursos entre as duas opções. Observe que os recursos de uma instância autônoma implantada por meio do marketplace do Azure mudam quando ela é descoberta no BlueXP .

[cols="3*"]
|===
|  | Mercado do Azure | BlueXP 


| *Onboarding* | Preparação mínima e mais curta, mínima necessária para a implantação direta | Processo de integração mais longo, incluindo a instalação do conetor BlueXP  


| *Tipos de máquina virtual (VM) suportados*  a| 
Tipos de instância EDS_v5 e LS_v3


NOTE: O tipo de instância L8s_v3 é suportado no marketplace do Azure para configurações de HA, mas não no BlueXP . O BlueXP  não será capaz de detectá-lo corretamente durante a descoberta.
| Gama completa de tipos de VM. https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurações compatíveis no Azure"^] 


| *Licença* | Licença gratuita | Qualquer licença baseada em capacidade. link:concept-licensing.html["Licenciamento do Cloud Volumes ONTAP"] 


| *Suporte NetApp* | Não incluído | Disponível, com base no tipo de licença 


| *Capacidade* | Até 500 GiB | Expansível por configuração 


| *Modelo de implantação* | Implantação do modo de alta disponibilidade (HA) em zona de disponibilidade única (AZ) | Todas as configurações compatíveis, incluindo os modos de nó único e HA, implantações de AZ únicas e várias 


| *Tipo de disco suportado* | Discos gerenciados premium SSD v2 | Suporte mais amplo. link:concept-storage.html#azure-storage["Configuração padrão para Cloud Volumes ONTAP"] 


| * Velocidade de gravação (modo de gravação rápida)* | Não suportado | Suportado, com base na sua configuração. link:concept-write-speed.html["Saiba mais sobre as velocidades de gravação no Cloud Volumes ONTAP"]. 


| *Recursos de orquestração* | Não disponível | Disponível através do BlueXP , com base no tipo de licença 


| *Número de VMs de armazenamento suportadas* | Uma por implantação | Várias VMs de storage, com base na sua configuração. link:task-managing-svms-azure.html#supported-number-of-storage-vms["Número suportado de VMs de storage"] 


| *Alterando o tipo de instância* | Não suportado | Suportado 


| *Disposição em camadas do FabricPool* | Não suportado | Suportado 
|===
.Links relacionados
* Implantação direta do Azure Marketplace: link:task-deploy-cvo-azure-mktplc.html["Implante o Cloud Volumes ONTAP a partir do marketplace do Azure"]
* Implantação do BlueXP : link:task-getting-started-azure.html["Início rápido para Cloud Volumes ONTAP no Azure"]
* https://docs.netapp.com/us-en/bluexp-family/index.html["Documentação do BlueXP"^]

