---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet 
summary: Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha uma configuração que atenda às suas necessidades. 
---
= Licenciamento do Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha um modelo de consumo que atenda às suas necessidades.



== Visão geral do licenciamento

As opções de licenciamento a seguir estão disponíveis para novos clientes.

Licenciamento baseado em capacidade:: Pague por vários sistemas Cloud Volumes ONTAP na sua conta do NetApp por capacidade provisionada. Inclui a capacidade de adquirir serviços de dados de nuvem complementares.
Inscrição no Keystone:: Um serviço baseado em subscrição com pagamento conforme o uso que proporciona uma experiência otimizada de nuvem híbrida para pares de alta disponibilidade (HA).


O modelo de licenciamento por nó anterior permanece disponível para clientes existentes que já compraram uma licença ou que tenham uma assinatura ativa do mercado.

As seções a seguir fornecem mais detalhes sobre cada uma dessas opções.


NOTE: O suporte não está disponível para o uso de recursos licenciados sem uma licença.



== Licenciamento baseado em capacidade

Os pacotes de licenciamento baseados em capacidade permitem que você pague por Cloud Volumes ONTAP por TIB de capacidade. A licença está associada à sua conta NetApp e permite que você carregue vários sistemas contra a licença, contanto que a capacidade suficiente esteja disponível através da licença.

Por exemplo, você pode comprar uma única licença TIB de 20 TB, implantar quatro sistemas Cloud Volumes ONTAP e alocar um volume de TIB de 5 TB para cada sistema, totalizando 20 TIB. A capacidade está disponível para os volumes em cada sistema Cloud Volumes ONTAP implantado nessa conta.

O licenciamento baseado em capacidade está disponível na forma de um _pacote_. Ao implantar um sistema Cloud Volumes ONTAP, você pode escolher entre vários pacotes de licenciamento com base nas necessidades da sua empresa.


NOTE: Embora o uso real e a medição dos produtos e serviços gerenciados no BlueXP  sejam sempre calculados em GiB e TIB, os termos GB/GiB e TB/TIB são usados de forma intercambiável. Isso é refletido nas listagens do Cloud Marketplace, cotações de preços, descrições de listagem e em outra documentação de suporte.



=== Pacotes

Os seguintes pacotes baseados em capacidade estão disponíveis para o Cloud Volumes ONTAP.

Para obter uma lista de tipos de VM suportados com os seguintes pacotes baseados em capacidade, consulte:

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurações compatíveis no Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurações compatíveis no Google Cloud"^]


endif::gcp[]



==== Freemium

Fornece todos os recursos do Cloud Volumes ONTAP gratuitamente da NetApp (taxas de provedor de nuvem ainda se aplicam).

* Nenhuma licença ou contrato é necessário.
* O suporte do NetApp não está incluído.
* Você está limitado a 500 GiB de capacidade provisionada por sistema Cloud Volumes ONTAP.
* Você pode usar até 10 sistemas Cloud Volumes ONTAP com a oferta Freemium por conta NetApp, em qualquer provedor de nuvem.
* Se a capacidade provisionada para um sistema Cloud Volumes ONTAP exceder 500 GiB, o BlueXP  converte o sistema no pacote Essentials.
+
Assim que um sistema é convertido para o pacote Essentials, o <<Notas sobre o carregamento,carga mínima>> aplica-se.

+
Quaisquer outros sistemas que tenham menos de 500 GiB de capacidade provisionada permanecem no Freemium (desde que sejam implantados usando a oferta do Freemium).





==== Otimizado

Pague por operações de e/S e capacidade provisionadas separadamente.

* Nó único ou HA da Cloud Volumes ONTAP
* O carregamento baseia-se em dois componentes de custo: Armazenamento e utilização (e/S).
+
Você não será cobrado por e/S relacionadas à replicação de dados (SnapMirror), backups (SnapVault) ou NDMP.



ifdef::azure[]

* Disponível no Azure Marketplace como uma oferta de pagamento conforme o uso ou como um contrato anual


endif::azure[]

ifdef::gcp[]

* Disponível no Google Cloud Marketplace como uma oferta de pagamento conforme o uso ou como um contrato anual


endif::gcp[]

* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra




==== Essenciais

Você pode pagar por capacidade em várias configurações diferentes:

* Escolha sua configuração do Cloud Volumes ONTAP:
+
** Um único nó ou sistema de HA
** Storage de arquivos e blocos ou dados secundários para recuperação de desastres (DR)


* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra


O licenciamento é baseado inteiramente no tipo de volume criado nos sistemas Cloud Volumes ONTAP:

* Nó único Essentials: Volumes de leitura/gravação criados em um sistema Cloud Volumes ONTAP usando apenas um nó ONTAP.
* Essentials HA: Volumes de leitura/gravação usando dois nós de ONTAP que podem fazer failover uns para os outros para acesso a dados sem interrupções.
* Nó único secundário do Essentials: Volumes do tipo de proteção de dados (normalmente volumes de destino SnapMirror ou SnapVault que são somente leitura) criados em um sistema Cloud Volumes ONTAP usando apenas um nó ONTAP.
+

NOTE: Se um volume somente leitura/DP se tornar um volume primário, o BlueXP  o considera como dados primários e os custos de carregamento são calculados com base no tempo em que o volume estava no modo de leitura/gravação. Quando o volume é novamente feito somente leitura/DP, a BlueXP  considera-o como dados secundários novamente e cobra de acordo com a licença mais adequada na carteira digital.

* Essentials secundário HA: Volumes do tipo de proteção de dados (DP) (normalmente volumes de destino SnapMirror ou SnapVault somente leitura) criados em um sistema Cloud Volumes ONTAP usando dois nós de ONTAP que podem fazer failover entre si para acesso a dados sem interrupções.


Observe estes pontos:

* Cobrança mínima: Há uma cobrança mínima de 4 TIB para cada VM de storage de fornecimento de dados que tenha pelo menos um volume primário (leitura-gravação). Para o pacote Essentials, essa cobrança mínima não se aplica às VMs de storage somente com volumes secundários (proteção de dados).
* Excedentes: Se a capacidade licenciada for excedida, os excedentes são cobrados pelas taxas de mercado, com preferência pela utilização da capacidade disponível de outras licenças em primeiro lugar.
* FlexClone e FlexCache volumes: O FlexClone volumes não é cobrado. Os volumes FlexCache de origem e destino são considerados dados primários e são cobrados de acordo com o espaço provisionado.
* Carregamento de pares HA: Para pares de HA, somente a capacidade provisionada em um nó é cobrada. Os dados espelhados de forma síncrona para o nó do parceiro não são cobrados.




==== Profissional

Pague por capacidade por qualquer tipo de configuração Cloud Volumes ONTAP com backups ilimitados.

* Fornece licenciamento para qualquer configuração do Cloud Volumes ONTAP
+
Nó único ou HA com carregamento de capacidade para volumes primários e secundários à mesma taxa

* Inclui backups de volume ilimitados usando backup e recuperação do BlueXP , mas apenas para sistemas Cloud Volumes ONTAP que usam o pacote profissional.
+

NOTE: Uma assinatura PAYGO é necessária para backup e recuperação do BlueXP , no entanto, não haverá cobrança por uso deste serviço. Para obter mais informações sobre como configurar o licenciamento para backup e recuperação do BlueXP , https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Configure o licenciamento para backup e recuperação do BlueXP "^] consulte .

* Adicione qualquer um dos serviços de dados de nuvem da NetApp a um custo extra




=== Modelos de consumo

Pacotes de licenciamento baseados em capacidade estão disponíveis com os seguintes modelos de consumo:

* *BYOL*: Uma licença adquirida na NetApp que pode ser usada para implantar o Cloud Volumes ONTAP em qualquer provedor de nuvem.


ifdef::azure[]

Observe que o pacote otimizado não está disponível com o BYOL.

endif::azure[]

* *PAYGO*: Uma assinatura por hora do mercado do seu provedor de nuvem.
* *Anual*: Um contrato anual do mercado do seu provedor de nuvem.


Observe o seguinte:

* Se você adquirir uma licença da NetApp (BYOL), também precisará assinar a oferta PAYGO no mercado do seu provedor de nuvem.
+
Sua licença sempre será cobrada primeiro, mas você será cobrado pela taxa por hora no mercado nestes casos:

+
** Se você exceder sua capacidade licenciada
** Se o prazo da sua licença expirar


* Se você tiver um contrato anual de um mercado, _All_ Cloud Volumes ONTAP sistemas que você implantar serão cobrados contra esse contrato. Você não pode misturar e combinar um contrato de mercado anual com o BYOL.
* Somente sistemas de nó único com BYOL são compatíveis nas regiões da China.




=== Mudando pacotes

Após a implantação, você pode alterar o pacote de um sistema Cloud Volumes ONTAP que usa licenciamento baseado em capacidade. Por exemplo, se você implantou um sistema Cloud Volumes ONTAP com o pacote Essentials, poderá alterá-lo para o pacote Professional se a sua empresa precisar ser alterada.

link:task-manage-capacity-licenses.html["Saiba como alterar os métodos de carregamento"].



=== Preços

Para obter detalhes sobre preços, https://cloud.netapp.com/pricing?hsCtaTracking=4f8b7b77-8f63-4b73-b5af-ee09eab4fbd6%7C5fefbc99-396c-4084-99e6-f1e22dc8ffe7["Site da NetApp BlueXP "^] visite .



=== Configurações compatíveis

Pacotes de licenciamento baseados em capacidade estão disponíveis com o Cloud Volumes ONTAP 9,7 e versões posteriores.



=== Limite de capacidade

Com esse modelo de licenciamento, cada sistema Cloud Volumes ONTAP individual dá suporte a até 2 PIB de capacidade por meio de discos e disposição em camadas no storage de objetos.

Não há limite máximo de capacidade quando se trata da própria licença.



=== Número máximo de sistemas

Com o licenciamento baseado em capacidade, o número máximo de sistemas Cloud Volumes ONTAP é limitado a 20 por conta do NetApp. Um _System_ é um par de HA do Cloud Volumes ONTAP, um sistema de nó único do Cloud Volumes ONTAP ou quaisquer VMs de storage adicionais que você criar. A VM de armazenamento padrão não conta com o limite. Este limite aplica-se a todos os modelos de licenciamento.

Por exemplo, digamos que você tenha três ambientes de trabalho:

* Um sistema Cloud Volumes ONTAP de nó único com uma VM de storage (essa é a VM de storage padrão criada quando você implanta o Cloud Volumes ONTAP)
+
Este ambiente de trabalho conta como um sistema.

* Um sistema Cloud Volumes ONTAP de nó único com duas VMs de storage (a VM de storage padrão e uma VM de storage adicional criada por você)
+
Esse ambiente de trabalho conta como dois sistemas: Um para o sistema de nó único e outro para a VM de storage adicional.

* Um par de HA do Cloud Volumes ONTAP com três VMs de storage (a VM de storage padrão e duas VMs de storage adicionais criadas por você)
+
Esse ambiente de trabalho conta como três sistemas: Um para o par de HA e dois para as VMs de storage adicionais.



São seis sistemas no total. Você teria então espaço para um sistema 14 adicional em sua conta.

Se você tiver uma implantação grande que exija mais de 20 sistemas, entre em Contato com o representante de sua conta ou com a equipe de vendas.

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["Saiba mais sobre as contas do NetApp"^].



=== Notas sobre o carregamento

Os detalhes a seguir podem ajudá-lo a entender como o carregamento funciona com licenciamento baseado em capacidade.



==== Carga mínima

Há uma cobrança mínima de 4 TIB para cada VM de storage de fornecimento de dados que tenha pelo menos um volume primário (leitura-gravação). Se a soma dos volumes primários for inferior a 4 TIB, o BlueXP  aplicará a carga mínima de 4 TIB a essa VM de armazenamento.

Se você ainda não provisionou nenhum volume, a cobrança mínima não se aplica.

Para o pacote Essentials, a taxa de capacidade mínima de 4 TIB não se aplica a VMs de armazenamento que contêm apenas volumes secundários (proteção de dados). Por exemplo, se você tiver uma VM de storage com 1 TIB de dados secundários, então você será cobrado apenas por 1 TIB de dados. Com todos os outros tipos de pacotes não essenciais (otimizado e profissional), a capacidade mínima de carregamento de 4 TIB aplica-se independentemente do tipo de volume.



==== Excesso de idade

Se você exceder sua capacidade BYOL ou se sua licença expirar, será cobrado por excesso de idade à taxa por hora com base na assinatura do marketplace.



==== Pacote Essentials

Com o pacote Essentials, você é cobrado pelo tipo de implantação (HA ou nó único) e pelo tipo de volume (primário ou secundário). Os preços de alta para baixa estão na seguinte ordem: _Essentials Primary HA_, _Essentials Primary Single Node_, _Essentials Secondary HA_ e _Essentials Secondary Single Node_. Como alternativa, quando você compra um contrato de mercado ou aceita uma oferta privada, as taxas de capacidade são as mesmas para qualquer tipo de implantação ou volume.

.BYOL
Se você comprou uma licença Essentials da NetApp (BYOL) e exceder a capacidade licenciada para esse tipo de implantação e volume, a carteira digital da BlueXP  cobra sobretaxas a uma licença Essentials de preço mais alto (se você tiver uma e houver capacidade disponível). Isso acontece porque primeiro usamos a capacidade disponível que você já comprou como capacidade pré-paga antes de cobrar no mercado. Se não houver capacidade disponível com sua licença BYOL, a capacidade excedida será cobrada nas taxas horárias sob demanda do mercado (PAYGO) e adicionará custos à sua fatura mensal.

Aqui está um exemplo. Digamos que você tenha as seguintes licenças para o pacote Essentials:

* Uma licença 500 TIB _Essentials Secondary HA_ que tem 500 TIB de capacidade comprometida
* Uma licença de nó único TIB _Essentials de 500 TIB que tenha apenas 100 TIB de capacidade comprometida


Outro 50 TIB é provisionado em um par de HA com volumes secundários. Em vez de cobrar esse 50 TIB ao PAYGO, a carteira digital BlueXP  cobra o excesso de TIB de 50 TIB contra a licença _Essentials Single Node_. Essa licença tem um preço superior ao _Essentials Secondary HA_, mas está fazendo uso de uma licença que você já comprou, e não adicionará custos à sua conta mensal.

Na carteira digital BlueXP , esse 50 TIB será mostrado como cobrado com a licença _Essentials Single Node_.

Aqui está outro exemplo. Digamos que você tenha as seguintes licenças para o pacote Essentials:

* Uma licença 500 TIB _Essentials Secondary HA_ que tem 500 TIB de capacidade comprometida
* Uma licença de nó único TIB _Essentials de 500 TIB que tenha apenas 100 TIB de capacidade comprometida


Outro 100 TIB é provisionado em um par de HA com volumes primários. A licença que você comprou não tem a capacidade comprometida _Essentials Primary HA_. A licença _Essentials Primary HA_ tem um preço superior às licenças _Essentials Primary Single Node_ e _Essentials Secondary HA_.

Neste exemplo, a carteira digital BlueXP  cobra sobretaxas à taxa de mercado para os 100 TIB adicionais. As taxas de excesso de idade aparecerão na sua conta mensal.

.Contratos de mercado ou ofertas privadas
Se você comprou uma licença Essentials como parte de um contrato de mercado ou uma oferta privada, a lógica BYOL não se aplica e você deve ter o tipo de licença exato para o uso. O tipo de licença inclui o tipo de volume (primário ou secundário) e o tipo de implantação (HA ou nó único).

Por exemplo, digamos que você implante uma instância do Cloud Volumes ONTAP com a licença Essentials. Depois, você provisiona volumes de leitura e gravação (nó único primário) e volumes somente leitura (nó único secundário). Seu contrato de mercado ou oferta privada deve incluir capacidade para _Essentials Single Node_ e _Essentials Secondary Single Node_ para cobrir a capacidade provisionada. Qualquer capacidade provisionada que não faça parte do seu contrato de mercado ou oferta privada será cobrada de acordo com as taxas por hora sob demanda (PAYGO) e adicionará custos à sua fatura mensal.



==== VMs de storage

* Não há custos adicionais de licenciamento para VMs de storage de fornecimento de dados (SVMs) adicionais, mas há uma cobrança de capacidade mínima de 4 TIB por SVM de fornecimento de dados.
* As SVMs de recuperação de desastres são cobradas de acordo com a capacidade provisionada.




==== Pares HA

Para pares de HA, você só será cobrado pela capacidade provisionada em um nó. Você não será cobrado pelos dados espelhados de forma síncrona para o nó do parceiro.



==== FlexClone e FlexCache volumes

* Não será cobrado pela capacidade usada pelo FlexClone volumes.
* Os volumes FlexCache de origem e destino são considerados dados primários e cobrados de acordo com o espaço provisionado.




=== Como começar

Saiba como começar a usar o licenciamento baseado em capacidade:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure o licenciamento para o Cloud Volumes ONTAP na AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure o licenciamento para o Cloud Volumes ONTAP no Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure o licenciamento para o Cloud Volumes ONTAP no Google Cloud"]


endif::gcp[]



== Inscrição no Keystone

Um serviço baseado em subscrição com pagamento conforme o uso que oferece uma experiência de nuvem híbrida otimizada para quem prefere modelos de consumo de despesas operacionais para CapEx adiantado ou aluguel.

O carregamento é baseado no tamanho da sua capacidade comprometida com um ou mais pares de HA da Cloud Volumes ONTAP na assinatura do Keystone.

A capacidade provisionada para cada volume é agregada e comparada com a capacidade comprometida periodicamente na sua assinatura do Keystone, e quaisquer excedentes são cobrados como o pico da sua assinatura do Keystone.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Saiba mais sobre o NetApp Keystone"^].



=== Configurações compatíveis

As assinaturas do Keystone são compatíveis com pares de HA. Esta opção de licenciamento não é suportada com sistemas de nó único no momento.



=== Limite de capacidade

Cada sistema Cloud Volumes ONTAP individual dá suporte a até 2 PIB de capacidade por meio de discos e disposição em camadas no storage de objetos.



=== Como começar

Saiba como começar a usar uma assinatura do Keystone:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure o licenciamento para o Cloud Volumes ONTAP na AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure o licenciamento para o Cloud Volumes ONTAP no Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure o licenciamento para o Cloud Volumes ONTAP no Google Cloud"]


endif::gcp[]



== Licenciamento baseado em nó

O licenciamento baseado em nó é o modelo de licenciamento da geração anterior que permitiu licenciar o Cloud Volumes ONTAP por nó. Este modelo de licenciamento não está disponível para novos clientes. O carregamento por nó foi substituído pelos métodos de carregamento por capacidade adicional descritos acima.


IMPORTANT: O NetApp encerrará a disponibilidade do licenciamento baseado em nós em breve. Após o término da disponibilidade, as licenças baseadas em nós precisarão ser convertidas em licenças baseadas em capacidade. Para obter informações, https://mysupport.netapp.com/info/communications/CPC-00589.html["Comunicado do cliente: CPC-00589"^] consulte .

O licenciamento baseado em nós ainda está disponível para clientes existentes:

* Se você tiver uma licença ativa, o BYOL estará disponível apenas para renovações de licença.
* Se você tiver uma assinatura ativa do marketplace, o carregamento ainda estará disponível por meio dessa assinatura.




== Conversões de licenças

Converter um sistema Cloud Volumes ONTAP existente para outro método de licenciamento não é suportado. Os três métodos de licenciamento atuais são o licenciamento baseado em capacidade, as assinaturas do Keystone e o licenciamento baseado em nós. Por exemplo, você não pode converter um sistema de licenciamento baseado em nó para licenciamento baseado em capacidade (e vice-versa).

Se você quiser fazer a transição para outro método de licenciamento, você pode comprar uma licença, implantar um novo sistema Cloud Volumes ONTAP usando essa licença e, em seguida, replicar os dados para esse novo sistema.

Observe que a conversão de um sistema do licenciamento por nó PAYGO para o licenciamento por nó BYOL (e vice-versa) não é suportada. Você precisa implantar um novo sistema e replicar dados para esse sistema. link:task-manage-node-licenses.html["Saiba como mudar entre PAYGO e BYOL"].
