---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado. 
---
= Limitações conhecidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.

Essas limitações são específicas para o gerenciamento de Cloud Volumes ONTAP no BlueXP . Para visualizar limitações com o próprio software Cloud Volumes ONTAP, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Vá para as Notas de versão do Cloud Volumes ONTAP"^]



== O BlueXP  não oferece suporte à criação de volumes do FlexGroup

Embora o Cloud Volumes ONTAP ofereça suporte ao FlexGroup volumes, o BlueXP  não oferece suporte à criação de volumes do FlexGroup no momento. Se você criar um volume do FlexGroup a partir do Gerenciador de sistemas do ONTAP ou da CLI do ONTAP, defina o modo de gerenciamento de capacidade do BlueXP  como Manual. O modo automático pode não funcionar corretamente com volumes FlexGroup.


NOTE: A capacidade de criar volumes do FlexGroup no BlueXP  está planejada para um lançamento futuro.



== BlueXP  não suporta S3 com Cloud Volumes ONTAP

Embora o Cloud Volumes ONTAP ofereça suporte ao S3 como opção para storage com escalabilidade horizontal, o BlueXP  não oferece recursos de gerenciamento para esse recurso. Usar a CLI é a melhor prática para configurar o acesso de cliente S3 a partir do Cloud Volumes ONTAP. Para obter mais informações, consulte http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 Guia de Energia de Configuração"^]a .

link:concept-client-protocols.html["Saiba mais sobre o suporte do Cloud Volumes ONTAP para S3 e outros protocolos de cliente"].



== O BlueXP  não oferece suporte à recuperação de desastres para VMs de storage

O BlueXP  não oferece qualquer configuração ou suporte de orquestração para recuperação de desastres de VM de storage (SVM). Use o Gerenciador de sistemas do ONTAP ou a CLI do ONTAP.

link:task-manage-svm-dr.html["Saiba mais sobre a recuperação de desastres do SVM"].
