---
sidebar: sidebar 
permalink: task-managing-svms-gcp.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver 
summary: Uma VM de armazenamento é uma máquina virtual em execução no ONTAP que fornece serviços de armazenamento e dados aos seus clientes. Você pode saber isso como um SVM ou um vserver. O Cloud Volumes ONTAP é configurado com uma VM de storage por padrão, mas algumas configurações oferecem suporte a VMs de storage adicionais. 
---
= Gerencie VMs de storage de fornecimento de dados para Cloud Volumes ONTAP no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Uma VM de armazenamento é uma máquina virtual em execução no ONTAP que fornece serviços de armazenamento e dados aos seus clientes. Você pode saber isso como um _SVM_ ou um _vserver_. O Cloud Volumes ONTAP é configurado com uma VM de storage por padrão, mas algumas configurações oferecem suporte a VMs de storage adicionais.

Para criar e gerenciar VMs de storage adicionais de fornecimento de dados no Google Cloud, use as APIs do BlueXP . Isso ocorre porque as APIs automatizam o processo de criação das VMs de storage e configuração das interfaces de rede necessárias. Ao criar as VMs de armazenamento, o BlueXP  configura os serviços de LIF necessários, bem como um iSCSI LIF necessário para comunicações SMB/CIFS de saída a partir da VM de armazenamento.

Para obter informações sobre a execução de chamadas de API do Cloud Volumes ONTAP, https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["Sua primeira chamada de API"^] consulte .



== Número suportado de VMs de storage

A partir do Cloud Volumes ONTAP 9,11.1, com base na sua licença, várias VMs de armazenamento são suportadas com configurações específicas. Consulte https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Notas de versão do Cloud Volumes ONTAP"^] para verificar o número de VMs de armazenamento suportadas para a sua versão do Cloud Volumes ONTAP.

Todas as versões do Cloud Volumes ONTAP anteriores a 9.11.1 oferecem suporte a uma VM de storage de fornecimento de dados e a uma VM de storage de destino usada para recuperação de desastres. Você pode ativar a VM de storage de destino para acesso aos dados se houver uma interrupção na VM de storage de origem.



== Crie uma VM de storage

Com base na configuração e no tipo de licença, você pode criar várias VMs de storage em um único sistema de nó ou em uma configuração de alta disponibilidade (HA) usando as APIs do BlueXP .

.Sobre esta tarefa
Quando você cria VMs de armazenamento usando as APIs, juntamente com a configuração das interfaces de rede necessárias, o BlueXP  também modifica as `default-data-files` políticas nas VMs de armazenamento de dados removendo os seguintes serviços do LIF de dados nas e adicionando-os ao LIF de dados iSCSI usado para conexões de gerenciamento de saída:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Antes de começar
O conetor requer permissões específicas para criar VMs de storage para pares de HA do Cloud Volumes ONTAP. As permissões necessárias estão incluídas no https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["As políticas fornecidas pela NetApp"^].



=== Sistema de nó único

Use a seguinte chamada de API para criar uma VM de storage em um sistema de nó único.

`POST /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

Inclua os seguintes parâmetros no corpo da solicitação:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== Par de HA

Use a seguinte chamada de API para criar uma VM de storage em um par de HA:

`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`

Inclua os seguintes parâmetros no corpo da solicitação:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
}
----


== Gerenciar VMs de storage

Com as APIs do BlueXP , você pode renomear e excluir VMs de storage em configurações de nó único e HA.

.Antes de começar
O conetor requer permissões específicas para gerenciar VMs de storage para pares de HA do Cloud Volumes ONTAP. As permissões necessárias estão incluídas no https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["As políticas fornecidas pela NetApp"^].



=== Renomeie uma VM de armazenamento

Para renomear uma VM de armazenamento, você deve fornecer os nomes da VM de armazenamento existente e da nova VM de armazenamento como parâmetros.

.Passos
* Use a seguinte chamada de API para renomear uma VM de armazenamento em um sistema de nó único:
+
`PUT /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

+
Inclua os seguintes parâmetros no corpo da solicitação:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Use a seguinte chamada de API para renomear uma VM de armazenamento em um par de HA:
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`

+
Inclua os seguintes parâmetros no corpo da solicitação:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Exclua uma VM de armazenamento

Em um único nó ou configuração de HA, você poderá remover uma VM de storage se ela não tiver volumes ativos.

.Passos
* Use a seguinte chamada de API para excluir uma VM de storage em um sistema de nó único:
+
`DELETE /gcp/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* Use a seguinte chamada de API para excluir uma VM de armazenamento em um par de HA:
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.Informações relacionadas
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Prepare-se para usar a API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Workflows do Cloud Volumes ONTAP"^]

