---
sidebar: sidebar 
permalink: task-planning-your-config-azure.html 
keywords: license, disk, storage, size, write speed, volume usage, byol, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, premium storage, standard storage, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported vm type, supported virtual machines, supported virtual machine types, supported instances, space, size, azure, disk size 
summary: Ao implantar o Cloud Volumes ONTAP no Azure, você pode escolher um sistema pré-configurado que corresponda aos requisitos de workload ou criar sua própria configuração. Se você escolher sua própria configuração, você deve entender as opções disponíveis para você. 
---
= Planeje sua configuração do Cloud Volumes ONTAP no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao implantar o Cloud Volumes ONTAP no Azure, você pode escolher um sistema pré-configurado que corresponda aos requisitos de workload ou criar sua própria configuração. Se você escolher sua própria configuração, você deve entender as opções disponíveis para você.



== Escolha uma licença Cloud Volumes ONTAP

Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha um modelo de consumo que atenda às suas necessidades.

* link:concept-licensing.html["Saiba mais sobre as opções de licenciamento para o Cloud Volumes ONTAP"]
* link:task-set-up-licensing-azure.html["Saiba como configurar o licenciamento"]




== Escolha uma região suportada

O Cloud Volumes ONTAP é compatível com a maioria das regiões do Microsoft Azure. https://bluexp.netapp.com/cloud-volumes-global-regions["Veja a lista completa de regiões suportadas"^].



== Escolha um tipo de VM compatível

O Cloud Volumes ONTAP suporta vários tipos de VM, dependendo do tipo de licença escolhido.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurações compatíveis com o Cloud Volumes ONTAP no Azure"^]



== Entenda os limites de armazenamento

O limite de capacidade bruta de um sistema Cloud Volumes ONTAP está vinculado à licença. Limites adicionais afetam o tamanho dos agregados e volumes. Você deve estar ciente desses limites à medida que planeja sua configuração.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["Limites de storage para Cloud Volumes ONTAP no Azure"^]



== Dimensione seu sistema no Azure

O dimensionamento do seu sistema Cloud Volumes ONTAP pode ajudar você a atender aos requisitos de performance e capacidade. Você deve estar ciente de alguns pontos-chave ao escolher um tipo de VM, tipo de disco e tamanho de disco:

Tipo de máquina virtual:: Observe os tipos de máquina virtual suportados no https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Notas de versão do Cloud Volumes ONTAP"^] e, em seguida, revise os detalhes sobre cada tipo de VM suportado. Esteja ciente de que cada tipo de VM suporta um número específico de discos de dados.
+
--
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv2-series["Documentação do Azure: Tamanhos de máquinas virtuais de uso geral"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Documentação do Azure: Tamanhos de máquina virtual otimizados para memória"^]


--
Tipo de disco Azure com sistemas de nó único:: Ao criar volumes para Cloud Volumes ONTAP, você precisa escolher o storage de nuvem subjacente que o Cloud Volumes ONTAP usa como disco.
+
--
Os sistemas de nó único podem usar esses tipos de discos gerenciados do Azure:

* _Discos gerenciados SSD premium_ fornecem alto desempenho para cargas de trabalho com uso intenso de e/S a um custo mais alto.
* Os discos gerenciados _Premium SSD v2_ fornecem um desempenho mais alto com menor latência a um custo menor, em comparação com os discos gerenciados SSD Premium.
* _Discos gerenciados SSD padrão_ fornecem desempenho consistente para cargas de trabalho que exigem IOPS baixo.
* _Discos gerenciados HDD padrão_ são uma boa escolha se você não precisa de IOPS alto e quer reduzir seus custos.


Para obter detalhes adicionais sobre os casos de uso desses discos, https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types["Documentação do Microsoft Azure: Que tipos de disco estão disponíveis no Azure?"^] consulte .

--
Tipo de disco Azure com pares de HA:: Os SISTEMAS HA usam discos gerenciados compartilhados SSD premium que oferecem alto desempenho para workloads com uso intenso de e/S a um custo mais alto. As implantações DE HA criadas antes da versão 9.12.1 usam blobs de página Premium.
Tamanho do disco do Azure::
+
--
Ao iniciar instâncias do Cloud Volumes ONTAP, você deve escolher o tamanho de disco padrão para agregados. O BlueXP  usa esse tamanho de disco para o agregado inicial e para quaisquer agregados adicionais que ele cria quando você usa a opção de provisionamento simples. Você pode criar agregados que usam um tamanho de disco diferente do padrão por link:task-create-aggregates.html["usando a opção alocação avançada"].


TIP: Todos os discos em um agregado devem ter o mesmo tamanho.

Ao escolher um tamanho de disco, você deve levar vários fatores em consideração. O tamanho do disco afeta o quanto você paga pelo storage, o tamanho dos volumes que pode criar em um agregado, a capacidade total disponível para o Cloud Volumes ONTAP e a performance de storage.

O desempenho do armazenamento Premium do Azure está vinculado ao tamanho do disco. Discos maiores fornecem IOPS e taxa de transferência mais altas. Por exemplo, a escolha de discos TIB de 1 TB pode fornecer melhor desempenho do que discos GiB de 500 TB, a um custo mais alto.

Não há diferenças de desempenho entre os tamanhos de disco para armazenamento padrão. Você deve escolher o tamanho do disco com base na capacidade que você precisa.

Consulte o Azure para ver IOPS e taxa de transferência por tamanho de disco:

* https://azure.microsoft.com/en-us/pricing/details/managed-disks/["Microsoft Azure: Preços de discos gerenciados"^]
* https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs/["Microsoft Azure: Preços de Blobs de páginas"^]


--




== Exibir discos do sistema padrão

Além do storage para dados de usuário, a BlueXP  também compra storage de nuvem para dados de sistema do Cloud Volumes ONTAP (dados de inicialização, dados de raiz, dados básicos e NVRAM). Para fins de Planejamento, pode ajudar você a analisar esses detalhes antes de implantar o Cloud Volumes ONTAP.

link:reference-default-configs.html#azure-single-node["Exibir os discos padrão para os dados do sistema Cloud Volumes ONTAP no Azure"].


TIP: O conetor também requer um disco do sistema. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["Exibir detalhes sobre a configuração padrão do conetor"^].



== Colete informações de rede

Ao implantar o Cloud Volumes ONTAP no Azure, você precisa especificar detalhes sobre sua rede virtual. Você pode usar uma Planilha para coletar as informações do administrador.

[cols="30,70"]
|===
| Informações do Azure | O seu valor 


| Região |  


| Rede virtual (VNet) |  


| Sub-rede |  


| Grupo de segurança de rede (se estiver usando o seu próprio) |  
|===


== Escolha uma velocidade de gravação

O BlueXP  permite que você escolha uma configuração de velocidade de gravação para o Cloud Volumes ONTAP. Antes de escolher uma velocidade de gravação, você deve entender as diferenças entre as configurações normal e alta e os riscos e recomendações ao usar alta velocidade de gravação. link:concept-write-speed.html["Saiba mais sobre a velocidade de escrita"].



== Escolha um perfil de uso de volume

O ONTAP inclui vários recursos de eficiência de storage que podem reduzir a quantidade total de storage de que você precisa. Ao criar um volume no BlueXP , você pode escolher um perfil que ative esses recursos ou um perfil que os desabilite. Você deve aprender mais sobre esses recursos para ajudá-lo a decidir qual perfil usar.

Os recursos de eficiência de storage da NetApp oferecem os seguintes benefícios:

Thin Provisioning:: Apresenta storage mais lógico para hosts ou usuários do que você realmente tem no pool de storage físico. Em vez de pré-alocar espaço de armazenamento, o espaço de armazenamento é alocado dinamicamente a cada volume à medida que os dados são gravados.
Deduplicação:: Melhora a eficiência localizando blocos idênticos de dados e substituindo-os por referências a um único bloco compartilhado. Essa técnica reduz os requisitos de capacidade de storage eliminando blocos redundantes de dados que residem no mesmo volume.
Compactação:: Reduz a capacidade física necessária para armazenar dados comprimindo dados dentro de um volume em armazenamento primário, secundário e de arquivo.

