---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: O Cloud Volumes ONTAP usa um link privado do Azure para conexões com suas contas de armazenamento associadas. Se necessário, você pode desativar os links privados do Azure e usar endpoints de serviço em vez disso. 
---
= Configurar a criação de grupo de posicionamento para pares de HA do Cloud Volumes ONTAP em AZs únicos da AWS
:allow-uri-read: 


[role="lead"]
As implantações de alta disponibilidade (HA) do Cloud Volumes ONTAP na zona de disponibilidade única (AZ) da AWS podem falhar e reverter se a criação do grupo de posicionamento falhar. A criação do grupo de posicionamento também falha e a implantação volta se o nó Cloud Volumes ONTAP e a instância de mediador não estiverem disponíveis. Para evitar isso, você pode modificar a configuração para permitir que a implantação seja concluída, mesmo que a criação do grupo de posicionamento falhe.

Ao ignorar o processo de reversão, o processo de implantação do Cloud Volumes ONTAP é concluído com êxito e notifica você que a criação do grupo de posicionamento está incompleta.

.Passos
. Use SSH para se conetar ao host do conetor e fazer login.
. Navegue até `/opt/application/netapp/cloudmanager/docker_occm/data`.
. Edite `app.conf` alterando o valor do `rollback-on-placement-group-failure` parâmetro para `false`. O valor padrão deste parâmetro é `true`.
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
. Guarde o ficheiro e termine a sessão no conetor. Não é necessário reiniciar o conetor.

