---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: Um volume FlexCache é um volume de storage que armazena em cache dados de leitura NFS de uma origem ou volume de origem. Leituras subsequentes para os dados armazenados em cache resultam em acesso mais rápido a esses dados. 
---
= Acelere o acesso aos dados com o FlexCache volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um volume FlexCache é um volume de storage que armazena em cache dados de leitura de SMB e NFS de um volume de origem (ou origem). Leituras subsequentes para os dados armazenados em cache resultam em acesso mais rápido a esses dados.

Você pode usar o FlexCache volumes para acelerar o acesso aos dados ou descarregar tráfego de volumes acessados com muita facilidade. Os volumes FlexCache ajudam a melhorar o desempenho, especialmente quando os clientes precisam acessar os mesmos dados repetidamente, porque os dados podem ser fornecidos diretamente sem ter que acessar o volume de origem. O FlexCache volumes funciona bem com workloads do sistema com uso intenso de leitura.

O BlueXP  fornece o gerenciamento do FlexCache volumes com o link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html["Armazenamento em cache de volume BlueXP"^] serviço.

Você também pode usar a CLI ou o Gerenciador de sistemas do ONTAP ONTAP para criar e gerenciar o FlexCache volumes:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["Guia de energia do FlexCache volumes para acesso mais rápido aos dados"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["Criando volumes FlexCache no Gerenciador de sistemas"^]


video::PBNPVRUeT1o[youtube,width=848,height=480]


== Trabalhe com o FlexCache quando a origem for criptografada

Ao configurar o FlexCache em um sistema Cloud Volumes ONTAP onde o volume de origem é criptografado, etapas adicionais são necessárias para garantir que o volume FlexCache possa acessar e armazenar adequadamente os dados criptografados.

.Antes de começar
. *Configuração de criptografia*: Certifique-se de que o volume de origem esteja totalmente criptografado e operacional. Para sistemas Cloud Volumes ONTAP, isso envolve a integração com serviços de gerenciamento de chaves específicos da nuvem.


ifdef::aws[]

Para a AWS, isso geralmente significa usar o AWS Key Management Service (KMS). Para obter informações, link:task-aws-key-management.html["Gerencie chaves com o AWS Key Management Service"]consulte .

endif::aws[]

ifdef::azure[]

Para o Azure, você precisa configurar o Azure Key Vault para criptografia de volume do NetApp (NVE). Para obter informações, link:task-azure-key-vault.html["Gerencie chaves com o Azure Key Vault"]consulte .

endif::azure[]

ifdef::gcp[]

Para o Google Cloud, é o Google Cloud Key Management Service. Para obter informações, link:task-google-key-manager.html["Gerencie chaves com o Cloud Key Management Service do Google"]consulte .

endif::gcp[]

. *Serviços de gerenciamento de chaves*: Antes de criar um volume FlexCache, verifique se os serviços de gerenciamento de chaves estão configurados corretamente no sistema Cloud Volumes ONTAP. Esta configuração é essencial para que o volume FlexCache descriptografe os dados do volume de origem.
. *Licenciamento*: Confirme se uma licença FlexCache válida está disponível e ativada no sistema Cloud Volumes ONTAP.
. *Versão ONTAP*: Certifique-se de que a versão ONTAP do seu sistema Cloud Volumes ONTAP suporte FlexCache com volumes criptografados. Consulte a matriz de compatibilidade ou mais recente https://docs.netapp.com/us-en/ontap/release-notes/index.html["Notas de versão do ONTAP"^] para obter mais informações.
. *Configuração de rede*: Certifique-se de que a configuração de rede permite uma comunicação perfeita entre o volume de origem e o volume FlexCache. Isso inclui roteamento adequado e resolução DNS em um ambiente de nuvem.


.Passos
Crie um volume FlexCache no seu sistema Cloud Volumes ONTAP com um volume de origem criptografado. Para obter instruções detalhadas e considerações adicionais, consulte as seguintes seções:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["Guia de energia do FlexCache volumes para acesso mais rápido aos dados"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["Criando volumes FlexCache no Gerenciador de sistemas"^]

