---
sidebar: sidebar 
permalink: task-connect-lun.html 
keywords: lun, connect lun, iscsi lun, target iqn, iqn 
summary: Quando cria um volume iSCSI, o BlueXP  cria automaticamente um LUN para si. Simplificamos a criação de apenas um LUN por volume, para que não haja gerenciamento envolvido. Depois de criar o volume, use o IQN para se conetar ao LUN a partir de seus hosts. 
---
= Conete um LUN a um host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando cria um volume iSCSI, o BlueXP  cria automaticamente um LUN para si. Simplificamos a criação de apenas um LUN por volume, para que não haja gerenciamento envolvido. Depois de criar o volume, use o IQN para se conetar ao LUN a partir de seus hosts.

Observe o seguinte:

* O gerenciamento automático de capacidade do BlueXP  não se aplica a LUNs. Quando o BlueXP  cria um LUN, ele desativa o recurso de crescimento automático.
* Você pode criar LUNs adicionais no Gerenciador de sistemas do ONTAP ou na CLI do ONTAP.


.Passos
. No menu de navegação à esquerda, selecione *Storage > Canvas*.
. Na página Canvas, clique duas vezes no ambiente de trabalho do Cloud Volumes ONTAP no qual você deseja gerenciar volumes.
. No ambiente de trabalho, clique na guia *volumes*.
. Na guia volumes, navegue até o título do volume desejado e clique em *Gerenciar volume* para acessar o painel direito Gerenciar volumes.
. Clique em *Target IQN*.
. Clique em *Copiar* para copiar o nome IQN.
. Configure uma conexão iSCSI do host para o LUN.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["Configuração expressa ONTAP 9 iSCSI para Red Hat Enterprise Linux: Iniciando as sessões iSCSI com o destino"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["Configuração expressa iSCSI ONTAP 9 para Windows: Iniciar sessões iSCSI com o destino"^]
** https://docs.netapp.com/us-en/ontap-sanhost/["Configuração de host SAN ONTAP"^]



