---
sidebar: sidebar 
permalink: task-planning-your-config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost 
summary: Ao implantar o Cloud Volumes ONTAP na AWS, você pode escolher um sistema pré-configurado que corresponda aos requisitos de workload ou criar sua própria configuração. Se você escolher sua própria configuração, você deve entender as opções disponíveis para você. 
---
= Planeje sua configuração do Cloud Volumes ONTAP na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao implantar o Cloud Volumes ONTAP na AWS, você pode escolher um sistema pré-configurado que corresponda aos requisitos de workload ou criar sua própria configuração. Se você escolher sua própria configuração, você deve entender as opções disponíveis para você.



== Escolha uma licença Cloud Volumes ONTAP

Várias opções de licenciamento estão disponíveis para o Cloud Volumes ONTAP. Cada opção permite que você escolha um modelo de consumo que atenda às suas necessidades.

* link:concept-licensing.html["Saiba mais sobre as opções de licenciamento para o Cloud Volumes ONTAP"]
* link:task-set-up-licensing-aws.html["Saiba como configurar o licenciamento"]




== Escolha uma região suportada

O Cloud Volumes ONTAP é compatível com a maioria das regiões da AWS. https://cloud.netapp.com/cloud-volumes-global-regions["Veja a lista completa de regiões suportadas"^].

As regiões mais recentes da AWS devem estar habilitadas para que você possa criar e gerenciar recursos nessas regiões. https://docs.aws.amazon.com/general/latest/gr/rande-manage.html["Saiba como habilitar uma região"^].



=== Escolha uma zona local suportada

O Cloud Volumes ONTAP é compatível com algumas zonas locais da AWS, incluindo Singapura. Selecionar uma zona local é opcional.

link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations/?nc=sn&loc=3["Veja a lista completa de zonas locais"^]. As zonas locais têm de estar ativadas antes de poder criar e gerir recursos nessas zonas.

link:https://aws.amazon.com/tutorials/deploying-low-latency-applications-with-aws-local-zones/["Saiba como ativar uma zona local"^].


NOTE: Phoenix não é uma zona local suportada.



== Escolha uma instância suportada

O Cloud Volumes ONTAP suporta vários tipos de instância, dependendo do tipo de licença escolhido.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configurações compatíveis com o Cloud Volumes ONTAP na AWS"^]



== Entenda os limites de armazenamento

O limite de capacidade bruta de um sistema Cloud Volumes ONTAP está vinculado à licença. Limites adicionais afetam o tamanho dos agregados e volumes. Você deve estar ciente desses limites à medida que planeja sua configuração.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html["Limites de storage para Cloud Volumes ONTAP na AWS"^]



== Dimensione seu sistema na AWS

O dimensionamento do seu sistema Cloud Volumes ONTAP pode ajudar você a atender aos requisitos de performance e capacidade. Você deve estar ciente de alguns pontos-chave ao escolher um tipo de instância, tipo de disco e tamanho de disco:

Tipo de instância::
+
--
* Faça a correspondência dos requisitos de workload com a taxa de transferência máxima e IOPS para cada tipo de instância do EC2.
* Se vários usuários gravarem no sistema ao mesmo tempo, escolha um tipo de instância que tenha CPUs suficientes para gerenciar as solicitações.
* Se você tem um aplicativo que é principalmente lido, então escolha um sistema com RAM suficiente.
+
** https://aws.amazon.com/ec2/instance-types/["Documentação da AWS: Tipos de instância do Amazon EC2"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["Documentação da AWS: Instâncias otimizadas do Amazon EBS"^]




--
Tipo de disco EBS:: A um nível elevado, as diferenças entre os tipos de discos EBS são as seguintes. Para saber mais sobre os casos de uso de discos EBS, http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentação da AWS: Tipos de volume do EBS"^] consulte .
+
--
* _Discos SSD de uso geral (GP3)_ são os SSDs de menor custo que equilibram custo e desempenho para uma ampla variedade de cargas de trabalho. O desempenho é definido em termos de IOPS e taxa de transferência. Os discos de GP3 tb são compatíveis com o Cloud Volumes ONTAP 9,7 e posterior.
+
Quando você seleciona um disco de GP3 tb, o BlueXP  preenche os valores de IOPS e taxa de transferência padrão que fornecem desempenho equivalente a um disco de GP2 tb com base no tamanho de disco selecionado. Você pode aumentar os valores para obter um melhor desempenho a um custo mais alto, mas não apoiamos valores mais baixos porque pode resultar em desempenho inferior. Em suma, mantenha os valores padrão ou aumente-os. Não os abaixe. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type["Saiba mais sobre discos GP3 e seu desempenho"^].

+
Observe que o Cloud Volumes ONTAP suporta o recurso volumes elásticos do Amazon EBS com discos GP3. link:concept-aws-elastic-volumes.html["Saiba mais sobre o suporte ao Elastic volumes"].

* _Discos SSD de uso geral (GP2)_ equilibram custo e desempenho para uma ampla variedade de cargas de trabalho. A performance é definida em termos de IOPS.
* _Os discos SSD IOPS provisionados (IO1)_ são para aplicativos críticos que exigem o mais alto desempenho a um custo mais alto.
+
Observe que o Cloud Volumes ONTAP suporta o recurso volumes elásticos do Amazon EBS com discos IO1. link:concept-aws-elastic-volumes.html["Saiba mais sobre o suporte ao Elastic volumes"].

* _Discos HDD otimizado para throughput (st1)_ são para cargas de trabalho acessadas com frequência que exigem taxa de transferência rápida e consistente a um preço menor.
+

NOTE: A disposição em camadas dos dados no storage de objetos não é recomendada quando se usa HDDs otimizados para taxa de transferência (st1).



--
Tamanho do disco EBS:: Se você escolher uma configuração que não suporte o link:concept-aws-elastic-volumes.html["Recurso de volumes elásticos do Amazon EBS"], precisará escolher um tamanho de disco inicial ao iniciar um sistema Cloud Volumes ONTAP. Depois disso, você pode link:concept-storage-management.html["Deixe o BlueXP  gerenciar a capacidade de um sistema para você"], mas se quiser link:task-create-aggregates.html["crie agregados você mesmo"], estar ciente do seguinte:
+
--
* Todos os discos em um agregado devem ter o mesmo tamanho.
* O desempenho dos discos EBS está ligado ao tamanho do disco. O tamanho determina o IOPS de linha de base e a duração máxima de intermitência para discos SSD e a taxa de transferência de linha de base e de intermitência para discos HDD.
* Em última análise, você deve escolher o tamanho do disco que lhe dá o _desempenho sustentado_ que você precisa.
* Mesmo que você escolha discos maiores (por exemplo, seis discos TIB de 4 TB), talvez você não tenha todos os IOPS porque a instância do EC2 pode atingir seu limite de largura de banda.
+
Para obter mais detalhes sobre o desempenho do disco EBS, http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentação da AWS: Tipos de volume do EBS"^] consulte .

+
Como observado acima, a escolha de um tamanho de disco não é suportada com configurações do Cloud Volumes ONTAP que suportam o recurso volumes elásticos do Amazon EBS. link:concept-aws-elastic-volumes.html["Saiba mais sobre o suporte ao Elastic volumes"].



--




== Exibir discos do sistema padrão

Além do storage para dados de usuário, a BlueXP  também compra storage de nuvem para dados de sistema do Cloud Volumes ONTAP (dados de inicialização, dados de raiz, dados básicos e NVRAM). Para fins de Planejamento, pode ajudar você a analisar esses detalhes antes de implantar o Cloud Volumes ONTAP.

link:reference-default-configs.html#aws["Exibir os discos padrão para os dados do sistema Cloud Volumes ONTAP na AWS"].


TIP: O conetor também requer um disco do sistema. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["Exibir detalhes sobre a configuração padrão do conetor"^].



== Prepare-se para implantar o Cloud Volumes ONTAP em um AWS Outpost

Se você tiver um AWS Outpost, você poderá implantar o Cloud Volumes ONTAP nesse Outpost selecionando a VPC Outpost no assistente ambiente de trabalho. A experiência é a mesma que qualquer outra VPC que reside na AWS. Observe que você precisará primeiro implantar um conetor no AWS Outpost.

Existem algumas limitações a apontar:

* No momento, apenas sistemas Cloud Volumes ONTAP de nó único são compatíveis
* As instâncias EC2 que você pode usar com o Cloud Volumes ONTAP estão limitadas ao que está disponível em seu Outpost
* Somente SSDs de uso geral (GP2) são suportados no momento




== Colete informações de rede

Ao iniciar o Cloud Volumes ONTAP na AWS, você precisa especificar detalhes sobre sua rede VPC. Você pode usar uma Planilha para coletar as informações do administrador.



=== Nó único ou par de HA em uma única AZ

[cols="30,70"]
|===
| Informações da AWS | O seu valor 


| Região |  


| VPC |  


| Sub-rede |  


| Grupo de segurança (se estiver usando o seu próprio) |  
|===


=== Par HA em várias AZs

[cols="30,70"]
|===
| Informações da AWS | O seu valor 


| Região |  


| VPC |  


| Grupo de segurança (se estiver usando o seu próprio) |  


| Zona de disponibilidade do nó 1 |  


| Sub-rede do nó 1 |  


| Zona de disponibilidade do nó 2 |  


| Sub-rede do nó 2 |  


| Zona de disponibilidade do mediador |  


| Sub-rede do mediador |  


| Par de chaves para o mediador |  


| Endereço IP flutuante para porta de gerenciamento de cluster |  


| Endereço IP flutuante para dados no nó 1 |  


| Endereço IP flutuante para dados no nó 2 |  


| Tabelas de rota para endereços IP flutuantes |  
|===


== Escolha uma velocidade de gravação

O BlueXP  permite que você escolha uma configuração de velocidade de gravação para o Cloud Volumes ONTAP. Antes de escolher uma velocidade de gravação, você deve entender as diferenças entre as configurações normal e alta e os riscos e recomendações ao usar alta velocidade de gravação. link:concept-write-speed.html["Saiba mais sobre a velocidade de escrita"].



== Escolha um perfil de uso de volume

O ONTAP inclui vários recursos de eficiência de storage que podem reduzir a quantidade total de storage de que você precisa. Ao criar um volume no BlueXP , você pode escolher um perfil que ative esses recursos ou um perfil que os desabilite. Você deve aprender mais sobre esses recursos para ajudá-lo a decidir qual perfil usar.

Os recursos de eficiência de storage da NetApp oferecem os seguintes benefícios:

Thin Provisioning:: Apresenta storage mais lógico para hosts ou usuários do que você realmente tem no pool de storage físico. Em vez de pré-alocar espaço de armazenamento, o espaço de armazenamento é alocado dinamicamente a cada volume à medida que os dados são gravados.
Deduplicação:: Melhora a eficiência localizando blocos idênticos de dados e substituindo-os por referências a um único bloco compartilhado. Essa técnica reduz os requisitos de capacidade de storage eliminando blocos redundantes de dados que residem no mesmo volume.
Compactação:: Reduz a capacidade física necessária para armazenar dados comprimindo dados dentro de um volume em armazenamento primário, secundário e de arquivo.

