---
sidebar: sidebar 
permalink: task-azure-image-export.html 
keywords: Azure, image, VHD, image signature file, export, marketplace, 
summary: Você pode exportar imagens do ONTAP do Azure Marketplace para verificar a assinatura do arquivo VHD. 
---
= Exportação de imagens do Azure Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Uma vez que a imagem VHD é publicada na nuvem Azure, a imagem não é mais gerenciada pelo NetApp. Em vez disso, a imagem publicada é colocada no marketplace do Azure. A alteração do Azure para o 1MB principal e o 512B final do VHD ocorre quando a imagem é encenada e publicada no marketplace do Azure. Para verificar a assinatura do arquivo VHD, a imagem VHD modificada pelo Azure precisa ser exportada primeiro do marketplace do Azure.

.O que você vai precisar
Tem de instalar os programas necessários no seu sistema.

* A CLI do Azure está instalada ou o Azure Cloud Shell por meio do portal do Azure está prontamente disponível.
+

NOTE: Para obter mais informações sobre como instalar a CLI do Azure, https://learn.microsoft.com/en-us/cli/azure/install-azure-cli["Documentação do Azure: Como instalar a CLI do Azure"^] consulte .



.Passos
. Mapeie a versão do ONTAP para a versão de imagem do marketplace do Azure usando o conteúdo do arquivo version_readme.
+
Para cada mapeamento de versão listado no arquivo version_readme, a versão do ONTAP é representada por "buildname", e a versão da imagem do marketplace do Azure é representada por "version".

+
Por exemplo, no seguinte arquivo version_readme, a versão do ONTAP "9.15.0P1" é mapeada para a versão "9150.01000024.05090105" da imagem do marketplace do Azure. Esta versão de imagem do marketplace do Azure é usada mais tarde para definir a URNA da imagem.

+
[listing]
----
[
    {
        "buildname": "9.15.0P1",
        "publisher": "netapp",
        "version": "9150.01000024.05090105"
    }
]
----
. Identifique o nome da região onde você pretende criar VMs.
+
Esse nome de região é usado como o valor para a variável "locName" ao definir a URNA da imagem do mercado.

+
.. Para receber uma lista de regiões disponíveis, digite o `az account list-locations -o table` comando.
+
Na tabela abaixo, o nome da região é chamado de campo "Nome".

+
[listing]
----
$ az account list-locations -o table
DisplayName               Name                 RegionalDisplayName
------------------------  -------------------  -------------------------------------
East US                   eastus               (US) East US
East US 2                 eastus2              (US) East US 2
South Central US          southcentralus       (US) South Central US
...
----


. Revise o nome do SKU para o tipo de implantação da VM correspondente na tabela abaixo.
+
O nome do SKU é usado como o valor para a variável "skuName" ao definir a URNA da imagem do mercado.

+
Por exemplo, as implantações de nó único devem usar o nome do SKU "ONTAP_cloud_byol".

+
[cols="1,1"]
|===
| Tipo de implantação da VM | Nome SKU 


| Nó único | ONTAP_cloud_byol 


| Alta disponibilidade | ONTAP_cloud_byol_ha 
|===
. Assim que a versão do ONTAP e a imagem do marketplace do Azure forem mapeadas, exporte o arquivo VHD do marketplace do Azure por meio do Azure Cloud Shell ou da CLI do Azure.




== Exporte o arquivo VHD por meio do Azure Cloud Shell no portal do Azure

. A partir do Azure Cloud Shell, exporte a imagem do mercado para um vhd (image2, por exemplo, 9150.01000024.05090105.vhd) e faça o download para sua máquina local (por exemplo, uma máquina Linux ou um PC Windows).
+
.Clique para apresentar
[%collapsible]
====
[source]
----
#Azure Cloud Shell on Azure portal to get VHD image from Azure Marketplace
a) Set the URN and other parameters of the marketplace image. URN is with format "<publisher>:<offer>:<sku>:<version>". Optionally, a user can list NetApp marketplace images to confirm the proper image version.
PS /home/user1> $urn="netapp:netapp-ontap-cloud:ontap_cloud_byol:9150.01000024.05090105"
PS /home/user1> $locName="eastus2"
PS /home/user1> $pubName="netapp"
PS /home/user1> $offerName="netapp-ontap-cloud"
PS /home/user1> $skuName="ontap_cloud_byol"
PS /home/user1> Get-AzVMImage -Location $locName -PublisherName $pubName -Offer $offerName -Sku $skuName |select version
...
141.20231128
9.141.20240131
9.150.20240213
9150.01000024.05090105
...

b) Create a new managed disk from the Marketplace image with the matching image version
PS /home/user1> $diskName = “9150.01000024.05090105-managed-disk"
PS /home/user1> $diskRG = “fnf1”
PS /home/user1> az disk create -g $diskRG -n $diskName --image-reference $urn
PS /home/user1> $sas = az disk grant-access --duration-in-seconds 3600 --access-level Read --name $diskName --resource-group $diskRG
PS /home/user1> $diskAccessSAS = ($sas | ConvertFrom-Json)[0].accessSas

c) Export a VHD from the managed disk to Azure Storage
Create a container with proper access level. As an example, a container named 'vm-images' with 'Container' access level is used here.
Get storage account access key, on Azure portal, 'Storage Accounts'/'examplesaname'/'Access Key'/'key1'/'key'/'show'/<copy>.
PS /home/user1> $storageAccountName = “examplesaname”
PS /home/user1> $containerName = “vm-images”
PS /home/user1> $storageAccountKey = "<replace with the above access key>"
PS /home/user1> $destBlobName = “9150.01000024.05090105.vhd”
PS /home/user1> $destContext = New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $storageAccountKey
PS /home/user1> Start-AzureStorageBlobCopy -AbsoluteUri $diskAccessSAS -DestContainer $containerName -DestContext $destContext -DestBlob $destBlobName
PS /home/user1> Get-AzureStorageBlobCopyState –Container $containerName –Context $destContext -Blob $destBlobName

d) Download the generated image to your server, e.g., a Linux machine.
Use "wget <URL of file examplesaname/Containers/vm-images/9150.01000024.05090105.vhd>".
The URL is organized in a formatted way. For automation tasks, the following example could be used to derive the URL string. Otherwise, Azure CLI 'az' command could be issued to get the URL, which is not covered in this guide. URL Example:
https://examplesaname.blob.core.windows.net/vm-images/9150.01000024.05090105.vhd

e) Clean up the managed disk
PS /home/user1> Revoke-AzDiskAccess -ResourceGroupName $diskRG -DiskName $diskName
PS /home/user1> Remove-AzDisk -ResourceGroupName $diskRG -DiskName $diskName
----
====




== Exporte o arquivo VHD através da CLI do Azure a partir da máquina Linux local

. Exporte a imagem do marketplace para um vhd através da CLI do Azure a partir de uma máquina Linux local.
+
.Clique para apresentar
[%collapsible]
====
[source]
----
#Azure CLI on local Linux machine to get VHD image from Azure Marketplace
a) Login Azure CLI and list marketplace images
% az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.

% az vm image list --all --publisher netapp --offer netapp-ontap-cloud --sku ontap_cloud_byol
...
{
"architecture": "x64",
"offer": "netapp-ontap-cloud",
"publisher": "netapp",
"sku": "ontap_cloud_byol",
"urn": "netapp:netapp-ontap-cloud:ontap_cloud_byol:9150.01000024.05090105",
"version": "9150.01000024.05090105"
},
...

b) Create a new managed disk from the Marketplace image with the matching image version
% export urn="netapp:netapp-ontap-cloud:ontap_cloud_byol:9150.01000024.05090105"
% export diskName="9150.01000024.05090105-managed-disk"
% export diskRG="new_rg_your_rg"
% az disk create -g $diskRG -n $diskName --image-reference $urn
% az disk grant-access --duration-in-seconds 3600 --access-level Read --name $diskName --resource-group $diskRG
{
  "accessSas": "https://md-xxxxxx.blob.core.windows.net/xxxxxxx/abcd?sv=2018-03-28&sr=b&si=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx&sigxxxxxxxxxxxxxxxxxxxxxxxx"
}

% export diskAccessSAS="https://md-xxxxxx.blob.core.windows.net/xxxxxxx/abcd?sv=2018-03-28&sr=b&si=xxxxxxxx-xxxx-xx-xx-xx&sigxxxxxxxxxxxxxxxxxxxxxxxx"
#To automate the process, the SAS needs to be extracted from the standard output. This is not included in this guide.

c) export vhd from managed disk
Create a container with proper access level. As an example, a container named 'vm-images' with 'Container' access level is used here.
Get storage account access key, on Azure portal, 'Storage Accounts'/'examplesaname'/'Access Key'/'key1'/'key'/'show'/<copy>. There should be az command that can achieve the same, but this is not included in this guide.
% export storageAccountName="examplesaname"
% export containerName="vm-images"
% export storageAccountKey="xxxxxxxxxx"
% export destBlobName="9150.01000024.05090105.vhd"

% az storage blob copy start --source-uri $diskAccessSAS --destination-container $containerName --account-name $storageAccountName --account-key $storageAccountKey --destination-blob $destBlobName

{
  "client_request_id": "xxxx-xxxx-xxxx-xxxx-xxxx",
  "copy_id": "xxxx-xxxx-xxxx-xxxx-xxxx",
  "copy_status": "pending",
  "date": "2022-11-02T22:02:38+00:00",
  "etag": "\"0xXXXXXXXXXXXXXXXXX\"",
  "last_modified": "2022-11-02T22:02:39+00:00",
  "request_id": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
  "version": "2020-06-12",
  "version_id": null
}

#to check the status of the blob copying
% az storage blob show --name $destBlobName --container-name $containerName --account-name $storageAccountName

....
    "copy": {
      "completionTime": null,
      "destinationSnapshot": null,
      "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx",
      "incrementalCopy": null,
      "progress": "10737418752/10737418752",
      "source": "https://md-xxxxxx.blob.core.windows.net/xxxxx/abcd?sv=2018-03-28&sr=b&si=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "status": "success",
      "statusDescription": null
    },
....

d) Download the generated image to your server, e.g., a Linux machine.
Use "wget <URL of file examplesaname/Containers/vm-images/9150.01000024.05090105.vhd>".
The URL is organized in a formatted way. For automation tasks, the following example could be used to derive the URL string. Otherwise, Azure CLI 'az' command could be issued to get the URL, which is not covered in this guide. URL Example:
https://examplesaname.blob.core.windows.net/vm-images/9150.01000024.05090105.vhd

e) Clean up the managed disk
az disk revoke-access --name $diskName --resource-group $diskRG
az disk delete --name $diskName --resource-group $diskRG --yes
----
====

