= Descoberta de implantações feitas pelo marketplace do Azure no BlueXP 
:allow-uri-read: 




=== Descoberta de implantações feitas pelo marketplace do Azure no BlueXP 

O BlueXP  agora tem a capacidade de descobrir os sistemas Cloud Volumes ONTAP implantados diretamente no marketplace do Azure. Isso significa que agora você pode adicionar e gerenciar esses sistemas como ambientes de trabalho no BlueXP , assim como qualquer outro sistema Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Implante o Cloud Volumes ONTAP a partir do marketplace do Azure"^]



=== Capacidade de categorizar dados para locatários do Azure

Agora você pode habilitar a disposição em camadas para um locatário do Azure em um cenário em que o ambiente de trabalho do Cloud Volumes ONTAP é criado por um locatário e o BlueXP  Connector é criado por outro. Usando essa funcionalidade, você pode usar o mesmo conetor para categorizar dados para vários locatários do Azure.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Requisitos para categorizar dados para um locatário do Azure"^]
